services:
  sec-assess:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enterprise-security-assessment-toolkit
    volumes:
      - ./reports:/app/reports
      - ./examples:/app/examples:ro
    working_dir: /app